language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install -g eslint istanbul
- npm install
script:
- istanbul cover test
- npm run eslint
after_success:
- npm install -g codecov
- codecov
